missions_list = [
    {"mission_name": "Train Heist",             "mission_type" :"Heist",       "location_options": ["Jungle", "City"],                                                 "challenge_1": "Environmental Obstacle",    "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Steal",                     "challenge_5": "Manmade Obstacle",          "challenge_6": "Getaway"},
    {"mission_name": "Artifact Heist",          "mission_type" :"Heist",       "location_options": ["Arctic Tundra", "Desert", "Jungle", "City"],                      "challenge_1": "Environmental Obstacle",    "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Steal",                     "challenge_5": "Environmental Obstacle",    "challenge_6": "Getaway"},
    {"mission_name": "Jewel Heist",             "mission_type" :"Heist",       "location_options": ["Arctic Tundra", "Desert", "Jungle", "City"],                      "challenge_1": "Environmental Obstacle",    "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Steal",                     "challenge_5": "Manmade Obstacle",          "challenge_6": "Getaway"},
    {"mission_name": "Steal Enemy Information", "mission_type" :"Heist",       "location_options": ["Arctic Tundra", "Desert", "Jungle", "City", "Ocean"],             "challenge_1": "Environmental Obstacle",    "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Steal",                     "challenge_5": "Security Obstacle",         "challenge_6": "Getaway"},
    {"mission_name": "Break Out Another Team",  "mission_type" :"Heist",       "location_options": ["Arctic Tundra", "Desert", "Jungle", "City"],                      "challenge_1": "Travel To Rendezvouz",      "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Contact Teammate/s",        "challenge_5": "Security Obstacle",         "challenge_6": "Getaway"},
    {"mission_name": "Escape Enemy Base",       "mission_type" :"Escape",      "location_options": ["Arctic Tundra", "Desert", "Jungle", "City"],                      "challenge_1": "Security Obstacle",         "challenge_2": "Manmade Obstacle",          "challenge_3": "Security Obstacle",         "challenge_4": "Getaway",                   "challenge_5": "Contact Teammate/s",        "challenge_6": "Travel To Rendezvouz"},
    {"mission_name": "Extract Another Team",    "mission_type" :"Rescue Op",   "location_options": ["Arctic Tundra", "Desert", "Jungle", "City", "Ocean", "Volcano"],  "challenge_1": "Contact Teammate/s",        "challenge_2": "Environmental Obstacle",    "challenge_3": "Travel To Rendezvouz",      "challenge_4": "Getaway",                   "challenge_5": "Environmental Obstacle",    "challenge_6": "Find Shelter"},
    {"mission_name": "Rescue Stranded Teammate","mission_type" :"Rescue Op",   "location_options": ["Arctic Tundra", "Desert", "Ocean", "Volcano"],                    "challenge_1": "System Failure",            "challenge_2": "Find Shelter",              "challenge_3": "Environmental Obstacle",    "challenge_4": "Contact Teammate/s",        "challenge_5": "Travel To Rendezvouz",      "challenge_6": "Environmental Obstacle"},
    {"mission_name": "Repair Research Base",    "mission_type" :"Survival",    "location_options": ["Arctic Tundra", "Desert", "Ocean", "Volcano"],                    "challenge_1": "Environmental Obstacle",    "challenge_2": "System Failure",             "challenge_3": "Environmental Obstacle",    "challenge_4": "Make Repairs",              "challenge_5": "Environmental Obstacle",    "challenge_6": "Make Repairs"},
    {"mission_name": "Get Rescued",             "mission_type" :"Survival",    "location_options": ["Arctic Tundra", "Desert", "Jungle", "Ocean", "Volcano"],          "challenge_1": "Environmental Obstacle",    "challenge_2": "Find Water",                "challenge_3": "Environmental Obstacle",    "challenge_4": "Find Shelter",              "challenge_5": "Contact Teammate/s",        "challenge_6": "Travel To Rendezvouz"},
    # Deactivate Bomb
    # Loot Wreck (Jungle - Aeroplane, Ocean - Ship)
    # Destroy our team's info in enemy base
    # Make a switch
    # Smuggle Goods?
    # Answer a Distress Signal
    # Deactivate Super Weapon
]